package = "t-doc-common"
version = "stable"
hermetic = true

[tags]
testing = "0.81"
stable = "0.81"
previous = "0.80"

[python]
minimum = "3.13"
recommend = "3.14"

[defaults]
command = ["tdoc", "site", "serve"]
command_10 = ["--open"]
command-dev = ["tdoc", "site", "serve", "--debug"]
command-dev_10 = ["--full-builds"]
