package = "t-doc-common"
version = "stable"
hermetic = true

[tags]
testing = "0.74"
stable = "0.74"
previous = "0.73"

[python]
minimum = "3.12"
recommend = "3.13"

[defaults]
command = ["tdoc", "site", "serve"]
command_10 = ["--open"]
command-dev = ["tdoc", "site", "serve", "--debug"]
command-dev_10 = ["--full-builds"]
