# Copyright 2024 Remy Blank <remy@c-space.org>
# SPDX-License-Identifier: MIT

name: Package
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Set up for running t-doc
        id: setup
        uses: t-doc-org/common/.github/actions/setup@main
        with:
          build-sites: false
          dev-pkgs: true
          ssh-key: ${{ secrets.DEPLOY_COMMON }}
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          path: repo
      - name: Build sdist and wheel
        working-directory: ./repo
        run: |
          uv build --out-dir=dist
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: python-package
          path: repo/dist/

  publish-to-pypi:
    name: Publish to PyPI
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/t-doc-common
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: python-package
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # v1.14.0
        with:
          print-hash: true

  publish-to-github:
    name: Publish to GitHub
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment:
      name: github
      url: https://github.com/t-doc-org/common/releases
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: python-package
          path: dist/
      - name: Sign packages
        uses: sigstore/gh-action-sigstore-python@5b79a39c381910c090341a2c9b0bf022c8b387e1  # v3.4.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create '${{ github.ref_name }}' \
              --repo='${{ github.repository }}' \
              --notes="[Release notes](https://common.t-doc.org/release-notes.html#release-$(echo '${{ github.ref_name }}' | sed -re 's/\./-/g'))"
      - name: Upload packages and signatures
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload '${{ github.ref_name }}' dist/* \
              --repo='${{ github.repository }}'
