# Copyright 2026 Remy Blank <remy@c-space.org>
# SPDX-License-Identifier: MIT

name: Test
on:
  push:
  workflow_dispatch:

jobs:
  setup-python:
    name: Set up Python
    uses: t-doc-org/common/.github/workflows/setup-python.yml@main
    with:
      build: true
  test-sites:
    name: Run test-sites.py
    needs: [setup-python]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Output Python version
        run: |
          ${{ needs.setup-python.outputs.python-path }} --version
