# Copyright 2026 Remy Blank <remy@c-space.org>
# SPDX-License-Identifier: MIT

name: Test
on:
  push:
  workflow_dispatch:

jobs:
  test-sites:
    name: Test sites
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        id: python
        uses: t-doc-org/common/.github/actions/setup-python@main
        with:
          build: true
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run site tests
        run: |
          ${{ steps.python.outputs.python-path }} tools/test-sites.py \
              test
