# Copyright 2024 Remy Blank <remy@c-space.org>
# SPDX-License-Identifier: MIT

[theme]
inherit = "sphinx_book_theme"
stylesheets = [
    "styles/sphinx-book-theme.css",
    "tdoc/styles.css",
]

[options]
enable_search_shortcuts = false  # Captures the '/' key
navigation_with_keys = false  # Captures <- and -> keys
